// <auto-generated />
namespace ClinicManagementSystem.Entities.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.4.4")]
    public sealed partial class ExaminationCorrections : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(ExaminationCorrections));
        
        string IMigrationMetadata.Id
        {
            get { return "202206211152076_ExaminationCorrections"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
