// <auto-generated />
namespace ClinicManagementSystem.Entities.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.4.4")]
    public sealed partial class AddressTest : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(AddressTest));
        
        string IMigrationMetadata.Id
        {
            get { return "202203242129426_AddressTest"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
